name: C build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]  # later: , macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ConorMacBride/install-package@v1
        with:
          # brew: TODO
          # brew-cask: TODO
          apt: python3-dev libiberty-dev clang libavahi-client-dev
          # choco: TODO
      - run: ./autogen.sh
      - run: ./configure
        if: ${{matrix.os}} == "ubuntu-latest"
      - run: ./configure --without-libiberty
        if: ${{matrix.os}} == "macOS-latest"
      - run: make
      - run: make check
